GET http://localhost:6969/api/doGetTaskLists?username=error




### Post req
POST http://localhost:6969/api/doPostNewList
Content-Type: application/json

{
    "name": "Task Name",
    "username": "error"
}