GET http://localhost:6969/api/doGetTaskLists?username=error




### Post req
POST http://localhost:6969/api/doPostNewList
Content-Type: application/json
username: mysterio

{
    "groupname": "Questionable list",
    "filename": "question"
}